import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Menu from './components/Menu'
import StyledComponentsRegistry from './lib/registry'
import { AuthProvider } from '../../providers/auth-providers'
import ThemeRegistry from '@/theme/ThemeRegistry/ThemeRegistry'
import { AppProvider } from '../../providers/appProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Team Collab',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ThemeRegistry>
            <StyledComponentsRegistry>
              <Menu>
                {children}
              </Menu>
            </StyledComponentsRegistry>
          </ThemeRegistry>

        </AuthProvider>
      </body>
    </html >
  )
}
